admin_template: admin-dist
agent_secret_key: 
avg_ping_count: 2
cover: 1
https: {}
install_host: 127.0.0.1:8008
ip_change_notification_group_id: 0
jwt_secret_key: 
jwt_timeout: 1
language: zh_CN
listen_port: 8008
location: Asia/Shanghai
site_name: 鸡子探针平台-柒蓝
tls: true
user_template: user-dist
